borrows/urls.py
from django.urls import path
from borrows import views


urlpatterns = [
    path('', views.index, name='index'),
    path('itens/', views.ItemListView.as_view(), name='itens'),
    path('item/<int:pk>', views.ItemDetailView.as_view(), name='item-detail'),
    path('pessoas/', views.PessoaListView.as_view(), name='pessoas'),
    path('pessoa/<int:pk>', views.PessoaDetailView.as_view(), name='pessoa-detail'),    
    path('sobre', views.sobre, name='sobre'),
    path('meuperfil', views.perfil, name='meu-perfil'),
    #path('accounts/profile', views.PerfilDetailView.as_view(), name='profile'),    

    path('item/create/', views.ItemCreate.as_view(), name='item_create'),
    path('item/<int:pk>/update/', views.ItemUpdate.as_view(), name='item_update'),
    path('item/<int:pk>/delete/', views.ItemDelete.as_view(), name='item_delete'),

    path('tipoitem/create/', views.TipoItemCreate.as_view(), name='tipoitem_create'),
    path('tipoitem/<int:pk>/update/', views.TipoItemUpdate.as_view(), name='tipoitem_update'),
    path('tipoitem/<int:pk>/delete/', views.TipoItemDelete.as_view(), name='tipoitem_delete'),

    path('signup', views.signup, name='signup'),
    path('perfil/<int:pk>/update/', views.PerfilUpdate.as_view(), name='perfil_update'),
    path('perfil/<int:pk>/delete/', views.PerfilDelete.as_view(), name='perfil_delete'),


    path('tipoitem/', views.TipoItemListView.as_view(), name='tipoitem'),
    path('meusitens/', views.MeusItensListView.as_view(), name='tipoitem'),
    path('meusemprestimos/', views.MeusEmprestimosListView.as_view(), name='meusemprestimos'),


    path('emprestimo/create/', views.EmprestimoCreate.as_view(), name='emprestimo_create'),
    path('emprestimo/<int:pk>/update/', views.EmprestimoUpdate.as_view(), name='emprestimo_update'),
    path('emprestimo/<int:pk>/delete/', views.EmprestimoDelete.as_view(), name='emprestimo_delete'),

    path('download/', views.download, name='download'),
    path('download_all/', views.downloadALL, name='download_all'),

    path('ari_mazer/', views.ari_mazer, name='ari_mazer'),

]

orcle_django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('borrows/', include('borrows.urls')),
]


urlpatterns += [
    path('', RedirectView.as_view(url='/borrows/')),
]

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

from . import settings
from borrows import views
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

borrows/models.py
from django.db import models
from django.contrib.auth.models import User
from orcle_django import settings
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _

# Create your models here.
class TipoItem(models.Model):
    nome = models.CharField(max_length=200, help_text='Digite o nome tipo de objeto')
    descricao = models.TextField("Descrição",max_length=1000, help_text='Insira uma breve descrição do tipo de objeto')
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.nome}'    

class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, primary_key=True)
    dt_nasc = models.DateField("Data de Nascimento",null=True, blank=True)
    cep = models.CharField(max_length=8, help_text='Digite o CEP do seu endereço')
    cidade = models.CharField(max_length=200)
    estado = models.CharField(max_length=2)
    pais = models.CharField(max_length=50)
    foto = models.ImageField(upload_to = 'profile_pics', default = 'profile_pics/no-image-icon.png')
    def __str__(self):
        """String for representing the Model object."""
        return f'{self.user.first_name} {self.user.last_name}'   

#Integração do Profile com User
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()


class Item(models.Model):
    nome = models.CharField(max_length=200, help_text='Digite o nome do objeto')
    autor = models.CharField(max_length=200, help_text='Digite o nome do autor, cantor, banda, criador, marca etc...')
    descricao = models.TextField("Descrição",max_length=1000, help_text='Insirta uma breve descrição do objeto')
    dono = models.ForeignKey(User, on_delete=models.CASCADE)
    tipo = models.ForeignKey('TipoItem', on_delete=models.SET_NULL, null=True, help_text='Selecione o tipo de objeto')
    foto = models.ImageField(upload_to = 'item_pics', default = 'item_pics/no-image-item.png')
    LOAN_STATUS = (
        ('e', 'Emprestado'),
        ('i', 'Indisponível'),
        ('d', 'Disponível'),
    )
    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        default='d',
        help_text='Status do item',
    )
    dtCadastro = models.DateTimeField("Cadastrado em",auto_now_add=True)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.tipo.nome}: {self.autor} - {self.nome} '


class Emprestimo(models.Model):
    dtEmprestimo = models.DateField("Data do Empréstimo")
    item = models.ForeignKey('Item', on_delete=models.CASCADE)
    pessoa = models.ForeignKey(User, on_delete=models.CASCADE)
    dtDevolucao = models.DateField("Data da Devolução",null=True)
    aberto = models.BooleanField(null=True)
    dtCadastro = models.DateTimeField("Cadastrado em",auto_now_add=True)

    class Meta:
        ordering = ['-aberto','-dtEmprestimo']

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.item.dono.first_name} {self.item.dono.last_name} emprestou o {self.item} para {self.pessoa.first_name} {self.pessoa.last_name}'

borrows/forms.py
from django import forms
from django.forms import ModelForm
from borrows.models import Item

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# from django.views.generic.edit import CreateView, UpdateView, DeleteView
# from django.urls import reverse_lazy


class SignUpForm(UserCreationForm):
    dt_nasc = forms.DateField(label="Data de Nascimento",help_text='Required. Format: YYYY-MM-DD')
    cep = forms.CharField(max_length=8)

    class Meta:
        model = User
        fields = ('username', 'first_name','last_name','email','dt_nasc', 'cep', 'password1', 'password2', )

# class ItemForm(ModelForm):
#     class Meta:
#         model = Item
#         fields = ['nome, autor, descricao, dono, tipo, foto, status']

# class ItemCreate(CreateView):
#     model = Item
#     fields = ['nome, autor, descricao, dono, tipo, foto, status']

# class ItemUpdate(UpdateView):
#     model = Item
#     fields = ['nome, autor, descricao, dono, tipo, foto, status']


# class ItemDelete(DeleteView):
#     model = Item
#     success_url = reverse_lazy('itens')    

borrows/views.py
from django.shortcuts import render, redirect
from borrows.models import TipoItem, Item, Profile, Emprestimo
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from django.views import generic
from orcle_django import settings
from borrows.forms import SignUpForm
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth import login, authenticate
from django import forms
import requests



def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.dt_nasc = form.cleaned_data.get('dt_nasc')
            user.profile.cep = form.cleaned_data.get('cep')
            viacep = 'http://viacep.com.br/ws/' + str(user.profile.cep) + '/json'
            r = requests.get(viacep)
            user.profile.cidade = r.json()['localidade']
            user.profile.estado = r.json()['uf']
            user.profile.pais = 'Brasil'
            #Usar requests para pegar cidade estado e pais
            user.save()
            user.profile.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('sobre')
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})




def index(request):
    """Página Inicial do site."""
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html')

@login_required
def sobre(request):
    
    # Render the HTML template index.html with the data in the context variable
    return render(request, 'sobre.html')

# --------------- Perfil ----------------------------------


class PerfilUpdate(LoginRequiredMixin,UpdateView):
    model = Profile
    fields = ['dt_nasc','cep','cidade','estado','pais','foto']
    success_url = reverse_lazy('itens')   


class PerfilDelete(LoginRequiredMixin,DeleteView):
    model = Profile
    success_url = reverse_lazy('itens')    

@login_required
def perfil(request):
    usuario = Profile.objects.get(pk=request.user)
    itens = Item.objects.filter(dono=request.user)
    nome = request.user.first_name + " " + request.user.last_name
    dt_nasc = usuario.dt_nasc
    foto = usuario.foto.url
    cidade = usuario.cidade
    estado = usuario.estado
    idusr = request.user.id

    listaitens = []
    for i in itens:
        dados = {
            'item': i
        }
        listaitens.append(i)

    #Criar Contexto
    context = {
        'nome'   : nome,
        'dt_nasc' : dt_nasc,
        'foto' : foto,
        'itens' : listaitens,
        'cidade' : cidade,
        'estado' : estado,
        'id' : idusr,

    }

    return render(request, 'meuperfil.html', context=context)




class MeusItensListView(LoginRequiredMixin, generic.ListView):
    model = Item   
    paginate_by = 3
    def get_queryset(self):
        return Item.objects.filter(dono=self.request.user)
    template_name = 'borrows/meusitens_list.html'


class ItemListView(LoginRequiredMixin, generic.ListView):
    model = Item   
    paginate_by = 3 

class TipoItemListView(LoginRequiredMixin, generic.ListView):
    model = TipoItem
    paginate_by = 4  

class ItemDetailView(LoginRequiredMixin, generic.DetailView):
    model = Item    

class PessoaListView(LoginRequiredMixin, generic.ListView):
    model = Profile
    paginate_by = 3    

class PessoaDetailView(LoginRequiredMixin, generic.DetailView):
    model = Profile        

# class PerfilDetailView(generic.DetailView):
#     model = Profile         




# class CadastraItem(ModelForm):
#     class Meta:
#         model = Item
#         fields = ['nome, autor, descricao, dono, tipo, foto, status']


# CRUD Genérico do Django
# --------------- Item ----------------------------------
class ItemCreate(LoginRequiredMixin,CreateView):
    model = Item
    fields = ['nome', 'autor', 'descricao', 'tipo', 'foto', 'status']
    success_url = reverse_lazy('itens')   

    def form_valid(self, form):
        form.instance.dono = self.request.user
        return super().form_valid(form)

class ItemUpdate(LoginRequiredMixin,UpdateView):
    model = Item
    fields = ['nome', 'autor', 'descricao', 'tipo', 'foto', 'status']
    success_url = reverse_lazy('itens')   


class ItemDelete(LoginRequiredMixin,DeleteView):
    model = Item
    success_url = reverse_lazy('itens')    

# --------------- TipoItem ----------------------------------

class TipoItemCreate(LoginRequiredMixin,CreateView):
    model = TipoItem
    fields = '__all__'
    success_url = reverse_lazy('itens')   

class TipoItemUpdate(LoginRequiredMixin,UpdateView):
    model = TipoItem
    fields = '__all__'
    success_url = reverse_lazy('itens')   


class TipoItemDelete(LoginRequiredMixin,DeleteView):
    model = TipoItem
    success_url = reverse_lazy('itens')    





# --------------- Empréstimo ----------------------------------


class MeusEmprestimosListView(LoginRequiredMixin, generic.ListView):
    model = Emprestimo   
    paginate_by = 4
    def get_queryset(self):
        usuario = self.request.user
        return Emprestimo.objects.filter(item__dono=usuario)
        #return Emprestimo.objects.all().filter(dono=usuario)
    template_name = 'borrows/meusemprestimos_list.html'


class EmprestimoCreate(LoginRequiredMixin,CreateView):
    model = Emprestimo
    fields = ['dtEmprestimo']
    dtEmprestimo = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    success_url = reverse_lazy('itens')   
    
    def form_valid(self, form):
        form.instance.pessoa = self.request.user
        form.instance.aberto = True
        i = Item.objects.get(pk=self.request.GET['item'])
        form.instance.item = i
        return super().form_valid(form)



class EmprestimoUpdate(LoginRequiredMixin,UpdateView):
    model = Emprestimo
    fields = ['dtDevolucao']
    dtDevolucao = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    success_url = reverse_lazy('itens')
    def form_valid(self, form):
        form.instance.aberto = True
        i = Item.objects.get(pk=form.instance.item.id)
        i.status = 'e'
        i.save()
        return super().form_valid(form)   


class EmprestimoDelete(LoginRequiredMixin,UpdateView):
    model = Emprestimo
    fields = ['dtDevolucao']
    dtDevolucao = forms.DateField(input_formats=settings.DATE_INPUT_FORMATS)
    success_url = reverse_lazy('itens') 
    
    def form_valid(self, form):
        form.instance.aberto = False
        i = Item.objects.get(pk=form.instance.item.id)
        i.status = 'd'
        i.save()
        return super().form_valid(form)   





#Servir arquivo

# import tarfile
# from io import BytesIO


# def serve_file(request):
#     out = BytesIO()
#     tar = tarfile.open(mode = "w:gz", fileobj = out)
#     data = 'lala'.encode('utf-8')
#     file = BytesIO(data)
#     info = tarfile.TarInfo(name="1.txt")
#     info.size = len(data)
#     tar.addfile(tarinfo=info, fileobj=file)
#     tar.close()

#     response = HttpResponse(out.getvalue(), content_type='application/tgz')
#     response['Content-Disposition'] = 'attachment; filename=myfile.tgz'
#     return response





@login_required
def download(request):
    import zipfile
    from django.http import HttpResponse
#Define dados do arquivo
    NOME = 'backup.json'
    itens = Item.objects.filter(dono = request.user)
    itemlist = '{'
    for i in itens:
        itemlist += "'"+str(i.id)+"'" + " : " + "'"+str(i)+"'" + ",\n"
    itemlist = itemlist[0:-3]
    itemlist += '}'
    ZIPFILE_NAME = 'orcle_meusitens.zip'



    response = HttpResponse(content_type='application/zip')
    zf = zipfile.ZipFile(response, 'w')
    zf.writestr(NOME, itemlist)
    response['Content-Disposition'] = f'attachment; filename={ZIPFILE_NAME}'
    return response


@login_required
def downloadALL(request):
    import zipfile
    from django.http import HttpResponse

    #Itens
    NOME_ITENS = 'itens.json'
    itens = Item.objects.all()
    itemlist = '{'
    for i in itens:
        novoitem = str(i.id) + ":{\n"
        novoitem += "\t'nome' :" + "'"+ str(i.nome) + "',\n"
        novoitem += "\t'autor' :" + "'"+ str(i.autor) + "',\n"
        novoitem += "\t'descricao' :" + "'"+ str(i.descricao) + "',\n"
        novoitem += "\t'dono' :" + "'"+ str(i.dono) + "',\n"
        novoitem += "\t'tipo' :" + "'"+ str(i.tipo) + "',\n"
        novoitem += "\t'foto' :" + "'"+ str(i.foto.url) + "',\n"
        novoitem += "\t'status' :" + "'"+ str(i.status) + "',\n"
        novoitem += "\t'dtCadastro' :" + str(i.dtCadastro) + "\n\t},\n"
        itemlist += novoitem    
    itemlist = itemlist[0:-2]
    itemlist += '\n}'
    
    #Perfis
    NOME_USUARIOS = 'users.json'
    usuarios = Profile.objects.all()
    usuariolist = '{'
    for u in usuarios:
        novousuario = str(u.user.id) + ":{\n"
        novousuario += "\t'dt_nasc' :" + "'"+ str(u.dt_nasc) + "',\n"
        novousuario += "\t'cep' :" + str(u.cep) + ",\n"
        novousuario += "\t'cidade' :" + "'"+ str(u.cidade) + "',\n"
        novousuario += "\t'estado' :" + "'"+ str(u.estado) + "',\n"
        novousuario += "\t'pais' :" + "'"+ str(u.pais) + "',\n"
        novousuario += "\t'foto' :" + "'"+ str(u.foto.url) + "\n\t},\n"
        usuariolist += novousuario    
    usuariolist = usuariolist[0:-2]
    usuariolist += '\n}'
    
    #Tipos de Item
    NOME_TIPOS = 'tipos.json'
    tipos = TipoItem.objects.all()
    tipolist = '{'
    for t in tipos:
        novotipo = str(t.id) + ":{\n"
        novotipo += "\t'nome' :" + "'"+ str(t.nome) + "',\n"

borrows/templates/borrows/emprestimo_form.html
{% extends "base_generic.html" %}
{% load bootstrap%}
{% block menu %}
  {% include "menu-bootstrap.html" %}
{% endblock %}

{% block content %}
<div class="container justify-content-center">
  <div class="container" style="text-align:center;">
      <h3>Pedir Emprestado</h3>
  </div>
  <div class="row justify-content-center">
  <div class="col-12 col-md-4">
    {{ form.non_field_errors }}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        {{ form|bootstrap }}
 
    <input type="submit" value="Cadastrar" class='btn btn-success'>
 
  </form>
</div>
</div>    
</div>    
{% endblock %}

borrows/templates/borrows/item_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Deletar Item</h1>

<p>Você tem certeza que deseja deletar o item : {{ item }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>

{% endblock %}

borrows/templates/borrows/item_detail.html
{% extends "base_generic.html" %}


{% block menu %}
  {% include "menu-bootstrap.html" %}
{% endblock %}

{% block content %}

<div class="row">
    <div class="col">


        <img class="detalhes_item_pic" src="{{ item.foto.url }}">
        <p> </p>
        <p><strong>Tipo: {{ item.tipo.nome }} </strong></p>

        <p><strong>Título: </strong>{{ item.nome }}</p>
        <p><strong>Autor:</strong> {{ item.autor }}</p> 
        <p><strong>Dono:</strong> {{ item.dono.first_name }} {{ item.dono.last_name }}</p> 
    
    </div>
</div>
<hr>
<div class="row">

        <div style="margin-left:20px;margin-top:20px">
                <h4>Emprestimos já feitos</h4>
            
                {% for e in item.emprestimo_set.all %}
                  <hr>
                  <i><p class="">Emprestado para {{ e.pessoa.first_name }} {{ e.pessoa.last_name }} em {{ e.dtEmprestimo }}</p></i>
                {% endfor %}
              </div>
</div>
{% endblock %}

borrows/templates/borrows/item_form.html
{% extends "base_generic.html" %}
{% load bootstrap %}
{% block menu %}
  {% include "menu-bootstrap.html" %}
{% endblock %}

{% block content %}
<div class="container">

  <div class="container col-6" style="text-align:center;">
      <h3>Cadastro de objeto</h3>
  </div>    
  <div class="row justify-content-center">
    {{ form.non_field_errors }}
    <form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
      {{ form|bootstrap}}
      
 
    <input type="submit" value="Cadastrar" class='btn btn-success btn-block'>
 
  </form>
</div>
</div>    
{% endblock %}

borrows/templates/borrows/item_list.html
{% extends "base_generic.html" %}


{% block menu %}
  {% include "menu-bootstrap.html" %}
{% endblock %}

{% block content %}
  <div class="row d-flex justify-content-center titulo_secao">
    <div class=".col-md-6 .offset-md-3 text-center">
        <span class="">Itens Disponíveis</span>
    </div>
    
  </div>
  {% if item_list %}
  <ul>
    {% for item in item_list %}
      <li>
          <div class="row justify-content-center">

                <div class="card mb-3 " style="width: 33rem;">
                    <img class="card-img-top" src="{{ item.foto.url }}">
                    <div class="card-body">
                        <h5 class="card-title"> {{ item }}</h5>
                        <p class="card-text">
                            Pertence a:  {{ item.dono.first_name }} {{ item.dono.last_name }} <br>
                        </p>
                        <p class="card-text"><small class="text-muted">Status: <span class="{% if item.status == 'd' %}disponivel{% elif item.status == 'i' %}indisponivel{% else %}emprestado{% endif %}">{{ item.get_status_display }}</span></small></p>
                        {% if item.status == 'd' %}
                        <!-- <div class="col "> -->
                          <a href="/borrows/emprestimo/create?item={{item.id}} "><button class="btn btn-primary float-right">Pedir Emprestado</button></a>
                        <!-- </div> -->
                        {% endif %}
                    </div>
                    <!-- <img class="item_pic" src="{{ item.foto.url }}">
                    <a href="/borrows/item/{{ item.id }}" >
                        <p class="nome_item">   {{ item }}</p>
                        <p class="dono_item"> 
                            Pertence a:  {{ item.dono.first_name }} {{ item.dono.last_name }} <br>
                            Status: <span class="{% if item.status == 'd' %}disponivel{% elif item.status == 'i' %}indisponivel{% else %}emprestado{% endif %}">{{ item.get_status_display }}</span>
                        </p>

                    </a> -->
  
                </div>

          </div>
      </li>
    {% endfor %}
    
  </ul>
  {% else %}
    <p>Nenhum item disponível.</p>
  {% endif %}
  {% if is_paginated %}
  <div class="pagination">
      <span class="page-links">
          {% if page_obj.has_previous %}
              <strong><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><span class="seta-pag">&#8592</span></a></strong>
          {% endif %}
          <span class="page-current">
              <sup>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</sup>
          </span>
          {% if page_obj.has_next %}
        <strong><a href="{{ request.path }}?page={{ page_obj.next_page_number }}"><span class="seta-pag">&#8594</span></a></strong>
          {% endif %}
      </span>
  </div>
  {% endif %}   
{% endblock %}

borrows/templates/borrows/meusemprestimos_list.html
{% extends "base_generic.html" %}


{% block menu %}
  {% include "menu-bootstrap.html" %}
{% endblock %}

{% block content %}
  <div class="row d-flex justify-content-center titulo_secao">
    <div class=".col-md-6 .offset-md-3 text-center">
        <span class="">Meus emprestimos Pendentes</span>
    </div>
    
  </div>
  {% if emprestimo_list %}
  <ul>
    {% for e in emprestimo_list %}
      <li>
        <div class="container bg-light p-2">


          <div class="row justify-content-center">
                <div class="col-12 col-md-6">
                        <p class="nome_item">   {{ e.item }}</p>
                        <p class="dono_item"> 
                            Solicitado por:  {{ e.pessoa.first_name }} {{ e.pessoa.last_name }} <br>
                        </p>
                </div>
                <div class="col-12 col-md-4">
                    {% if e.aberto == True%}
                    <a href="/borrows/emprestimo/{{e.id}}/update"><button class="btn btn-primary btn-block">
                           {% if e.dtDevolucao == Null%} 
                            
                            Confirmar

                            {% else %}

                            Alterar data de Devolução

                            {% endif %}
                        
                        </button></a>
                        {% if e.item.status == 'e'%}
                        <a href="/borrows/emprestimo/{{e.id}}/delete">
                        <button class="btn btn-secondary btn-block">Cadastrar Devolução</button>
                        </a>
                        {% endif %}
    
                    {% endif %}
                </div>


          </div>
        </div>
      </li>
      <br>
    {% endfor %}
    
  </ul>
  {% else %}
    <p>Nenhum item disponível.</p>
  {% endif %}
  {% if is_paginated %}
  <div class="pagination">
      <span class="page-links">
          {% if page_obj.has_previous %}
              <strong><a href="{{ request.path }}?page={{ page_obj.previous_page_number }}"><span class="seta-pag">&#8592</span></a></strong>
          {% endif %}
          <span class="page-current">
              <sup>Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.</sup>
          </span>
          {% if page_obj.has_next %}
        <strong><a href="{{ request.path }}?page={{ page_obj.next_page_number }}"><span class="seta-pag">&#8594</span></a></strong>
          {% endif %}
      </span>
  </div>
  {% endif %}       
{% endblock %}

borrows/templates/borrows/meusitens_list.html
{% extends "base_generic.html" %}


{% block menu %}
  {% include "menu-bootstrap.html" %}
{% endblock %}

{% block content %}
  <div class="row d-flex justify-content-center titulo_secao">
    <div class=".col-md-6 .offset-md-3 text-center">
        <span class="">Meus Itens Disponíveis</span>
    </div>
    
  </div>
  {% if item_list %}
  <div class="row justify-content-center">
  <ul>
    {% for item in item_list %}
      <li class="">
          <div class="card " style="width: 18rem;">
                <div class="card-body">
                    <img class="card-img-top" src="{{ item.foto.url }}">
                        <h5 class="card-title">   {{ item }}</h5>
                        <p class="card-text"> 
                            Pertence a:  {{ item.dono.first_name }} {{ item.dono.last_name }} <br>
                            Status: <span class="{% if item.status == 'd' %}text-success{% elif item.status == 'i' %}text-danger{% else %}text-warning{% endif %}">{{ item.get_status_display }}</span>
                        </p>
                        <a href="/borrows/item/{{item.id}}/update"><button class="btn btn-warning btn-block">Alterar</button></a>
                        <a href="/borrows/item/{{item.id}}/delete"><button class="btn btn-danger btn-block">Excluir</button></a>

                </div>

          </div>
      </li>
    {% endfor %}
    
  </ul>
</div>
  {% else %}
    <p>Nenhum item disponível.</p>
  {% endif %}
  {% if is_paginated %}
  <div class="pagination">
      <span class="page-links">
          {% if page_obj.has_previous %}
              <a href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
          {% endif %}
          <span class="page-current">
              Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
          </span>
          {% if page_obj.has_next %}
              <a href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
          {% endif %}
      </span>
  </div>
  {% endif %}       
{% endblock %}

borrows/templates/borrows/profile_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Deletar Tipo de Item</h1>

<p>Você tem certeza que deseja deletar o sua conta?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" class='btn btn-danger' value="Sim.">
</form>

{% endblock %}